# 通用配置
project_name: "ml-project"
seed: 42
deterministic: true         # 可复现性（注意会稍降吞吐）
precision: 16               # 混合精度训练：16 或 32
num_workers: 4
pin_memory: true
cudnn_benchmark: true       # 若deterministic为true会被覆盖

task: "image_classification"  # 或 "tabular_classification"

paths:
  data_dir: "data/processed"
  outputs_dir: "outputs"
  ckpt_dirname: "checkpoints"

dataset:
  name: "ImageFolderCSV"     # 或 "TabularCSVDataset"
  train_csv: "train.csv"     # 约定：相对 data_dir
  val_csv: "val.csv"
  test_csv: "test.csv"
  input_col: "path"          # 图像：文件路径列；表格：也可不用
  label_col: "label"
  class_map_path: "class_index.json"  # 自动生成/读取
  # 表格时需要：
  # numeric_cols: [feat1, feat2, ...]
  # cat_cols: [cat1, cat2, ...]

transforms:
  image_size: 224
  aug:
    random_flip: true
    random_crop: true
    color_jitter: false

model:
  name: "resnet18"           # image: resnet18/resnet50；tabular: mlp
  num_classes: null          # 自动从数据推断
  pretrained: true

optimizer:
  name: "adamw"
  lr: 3e-4
  weight_decay: 0.01

scheduler:
  name: "cosine"
  warmup_epochs: 1

trainer:
  max_epochs: 30
  batch_size: 64
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  devices: 1
  accelerator: "auto"        # "gpu" / "cpu" / "auto"
  log_every_n_steps: 10
  val_check_interval: 1.0    # 每个epoch验证一次

callbacks:
  early_stopping:
    monitor: "val/acc"
    mode: "max"
    patience: 5
  model_checkpoint:
    monitor: "val/acc"
    mode: "max"
    save_top_k: 1
    save_last: true
